[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.idea
  | _build
  | build
  | dist
  | misc
)/
'''
[tool.isort]
line_length=79
known_first_party="erevan_booking"
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
